version: "3.9"

services:
  ### Auth Service
  auth-service:
    container_name: auth-service
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    ports:
      - "4001:4001"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://auth-db:5432/auth-service-db
      SPRING_DATASOURCE_USERNAME: username
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - auth-db
    networks:
      - swift-network

  ### PostgreSQL for Auth Service
  auth-db:
    image: postgres:latest
    container_name: auth-db
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: auth-service-db
      PGDATA: /data/postgres
    volumes:
      - auth_service_data:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - swift-network

volumes:
  auth_service_data:

networks:
  swift-network:
    driver: bridge
