spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service-route
              uri: http://auth-service:4001
              predicates:
                - Path=/auth/**, /oauth2/**, /login/oauth2/**
              filters:
                - StripPrefix=0

server:
  port: 4000

auth:
  service:
    url: ${AUTH_SERVICE_URL}